package com.example.telegramanimalshelterholiday.constants.enums;

public enum BotState {
    CHOICES_SHELTER,
    SHELTER_DOG,
    SHELTER_CAT,
    STAGE_INFO_DOG,
    STAGE_INFO_CAT,
    STAGE_ADOPTER_IN_ADOPTION_INFO_MENU_CAT,
    STAGE_ADOPTER_IN_ADOPTION_INFO_MENU_DOG,
   STAGE_WAITING_FOR_PET_PICTURE,
    STAGE_WAITING_FOR_PET_DIET,
    STAGE_WAITING_FOR_WELL_BEING,
    WAITING_FOR_BEHAVIOR_CHANGE,
    DEFAULT
}
